/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/izin-talebi` | `/izin-talebi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/izinlerim` | `/izinlerim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onaylar` | `/onaylar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/izin-talebi` | `/izin-talebi`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/izinlerim` | `/izinlerim`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onaylar` | `/onaylar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/izin-talebi${`?${string}` | `#${string}` | ''}` | `/izin-talebi${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/izinlerim${`?${string}` | `#${string}` | ''}` | `/izinlerim${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onaylar${`?${string}` | `#${string}` | ''}` | `/onaylar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/izin-talebi` | `/izin-talebi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/izinlerim` | `/izinlerim`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onaylar` | `/onaylar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; };
    }
  }
}
